;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        counsel-yank-pop
        ivy-wgrep-change-to-wgrep-mode
        markdown-outdent-or-delete
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-insert-todo-heading
        org-kill-line
        org-metaleft
        org-self-insert-command
        org-shiftcontrolright
        org-shiftmetaright
        org-todo
        rtags-find-references-at-point
        sd/comment-line-or-region
        sd/copy-word-under-cursor
        sd/forward-or-backward-sexp
        sd/mark-from-point-to-end-of-line
        sd/whole-line-or-region-kill-ring-save
        transpose-words
        undefined
        wdired-finish-edit
        wgrep-finish-edit
        whole-line-or-region-kill-region
        yank
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        company-complete
        counsel-M-x
        ff-find-other-file
        isearch-forward-regexp
        mouse-set-region
        org-table-copy-down
        rtags-find-symbol
        rtags-imenu
        sd/rtags-find-symbol-at-point
        sp-slurp-hybrid-sexp
        yank-rectangle
        ))
