;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        counsel-yank-pop
        markdown-outdent-or-delete
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-insert-todo-heading
        org-metaleft
        org-self-insert-command
        org-shiftcontrolright
        org-shiftmetaright
        rtags-find-references-at-point
        sd/comment-line-or-region
        sd/copy-word-under-cursor
        sd/mark-from-point-to-end-of-line
        sd/whole-line-or-region-kill-ring-save
        wdired-finish-edit
        whole-line-or-region-kill-region
        yank
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        company-complete
        counsel-M-x
        ff-find-other-file
        mouse-set-region
        rtags-imenu
        yank-rectangle
        ))
